### ISSUE TITLE
New PCB

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#10]
After chatting with Dr. Palmeri this morning I edited my PCB a little. I basically wanted to use a Nano instead of an Uno. Does this seem okay?

**Comment by mlp6** [comment]
It looks like your board is effectively superimposed onto the Nano instead of a being a separate board that would plug into the top of the Nano.  Instead of having the Nano on the schematic, you just want to capture the header pin layout and use that instead of the Nano itself.

**Comment by a-poorva** [comment]
Updated. Does this look better?

**Comment by sphaerobolus** [comment]
We may have regressed here. I'm sorry for the circular nature.  

What's the plan for attaching the Arduino? This board won't directly plug in either the Uno or Nano. 

Also, it appears there are no ground connections to the headers on the board. 

The bottom-side trace N$6 passes too close to a couple of header pins. If you wanted to route N$6 on the top side, you could. I see at least one easy, albeit convoluted, route for it. But what's the purpose of connecting one Arduino pin to another Arduino pin and nothing else? These pin connections don't seem to be reflected in the schematic. Am I missing something?
