### ISSUE TITLE
Magnet Idea

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#11]
After considering Matt's feedback (the cylinder thing is still on the table, I'm looking into the information he sent me {thanks Matt!}), I had an alternate idea which you can find in the Mechanical Design folder. 

Here, I wanted to have the lid snap on to the box with a magnet - i.e, I would have a magnetic strip along the edge of the lid and the box (around 1 mm width). 

Would that be possible?

**Comment by sphaerobolus** [comment]
Certainly possible. I have many magnets sitting around, but they're all significantly larger than that. See if you can find something at kjmagnetics.com

**Comment by a-poorva** [comment]
Will do, thank you!
