### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#13]
Hello,

My PCB hasn't been working the last few times, so I just wanted to be sure that this circuit makes sense before I etched another board. @sphaerobolus @mlp6 would you mind taking a look?

**Comment by mlp6** [comment]
What specifically isn't working when you're attempting to use it?

**Comment by a-poorva** [comment]
Neither the LED nor the button were working in the previous boards, nor was the Arduino powered on, though I had connected the battery to the right pins? 

Which is why I was wondering if my circuit makes sense on the board, since this seems to work on the breadboard - unless I'm drawing the schematic wrong, as well.

**Comment by mlp6** [comment]
okey dokey - I'll take a peek this evening
