### ISSUE TITLE
Header pins

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#8]
I just realised that I used the arduino board in my PCB instead of header pins. Is this the right way to do this? I'm not sure I understand the difference here.

**Comment by sphaerobolus** [comment]
If you want this to be a shield for your Uno, you need to line up your connections to the Uno. To do this, you placed the Uno board as a component. If I understand you correctly, you might just be confused over semantics. Are you placing the Uno on your board? Or your board on the Uno? Doesn't matter, the holes still line up. 

After fabricating the board, you'll put header pins in all those holes around the perimeter, then plug your board into the Uno. 

Did I answer the right question?

**Comment by a-poorva** [comment]
Right, so it doesn't matter, essentially, whether you use header pins or the actual board in your design, as long as the pins line up?

**Comment by mlp6** [comment]
Yep!
